# Generated by Django 4.1.5 on 2023-01-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="screenShot_images",
            field=models.ImageField(
                default="default.jpg", upload_to="ScreenShot_images"
            ),
        ),
    ]
